### ISSUE TITLE
AttributeError: 'ColoredFormatter' object has no attribute 'find'

### ISSUE THREAD

**Issue by sanfx** [borntyping/python-colorlog#22]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 859, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 732, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 472, in format
    if self.usesTime():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/__init__.py", line 456, in usesTime
    return self._fmt.find("%(asctime)") >= 0
AttributeError: 'ColoredFormatter' object has no attribute 'find'

**Comment by borntyping** [comment]
Can you show how you are setting up the formatter? I can't see why `self._fmt` would ever be set to a `ColoredFormatter` object.

**Comment by sanfx** [comment]
I couldn't remember how I did it initially that caused this error but later I added like this
```
handler.setFormatter(formatter)
```
and it worked,
