### ISSUE TITLE
Error with reset color and style "{" on Python 3.6

### ISSUE THREAD

**Issue by thorstenkampe** [borntyping/python-colorlog#36]
Python 3.6.0a4 64-bit on Windows

The following code produces an error with Python 3.6 but not Python 3.5:

```
import logging, colorlog

logger  = logging.getLogger()
handler = logging.StreamHandler()

handler.setFormatter(colorlog.ColoredFormatter(
    '{log_color}{levelname}:{reset} {message}', style = '{'))

logging.getLogger().addHandler(handler)

logger.error('TEST')
```

```
--- Logging error ---
Traceback (most recent call last):
  File "F:\PortableApps\Python3x\lib\logging\__init__.py", line 985, in emit
    msg = self.format(record)
  File "F:\PortableApps\Python3x\lib\logging\__init__.py", line 831, in format
    return fmt.format(record)
  File "F:\PortableApps\Python3x\lib\site-packages\colorlog\colorlog.py", line 129, in format
    message = super(ColoredFormatter, self).format(record)
  File "F:\PortableApps\Python3x\lib\logging\__init__.py", line 571, in format
    s = self.formatMessage(record)
  File "F:\PortableApps\Python3x\lib\logging\__init__.py", line 540, in formatMessage
    return self._style.format(record)
  File "F:\PortableApps\Python3x\lib\logging\__init__.py", line 392, in format
    return self._fmt.format(**record.__dict__)
KeyError: 'reset'
Call stack:
  File "test.py", line 11, in <module>
    logger.error('TEST')
Message: 'TEST'
Arguments: ()
```

**Comment by borntyping** [comment]
Python 3.6 appears to have changed some behavior, and does not call the `__missing__()` method of the `__dict__` a `ColoredRecord` provides. Not sure how to fix this, other than reimplementing even more of the `logging` internals.

**Comment by lahwaacz** [comment]
Considering that Python 3.6 is stable since Christmas, maybe this should be finally fixed or worked around somehow.

**Comment by borntyping** [comment]
@lahwaacz You're welcome to provide a patch yourself. I've been on holiday and have not had time to work on it yet.

**Comment by borntyping** [comment]
This only seems to happen when using the root logger (`logging.getLogger()`).

When the record is passed in, `__getattr__` doesn't get called for missing keys.

**Comment by borntyping** [comment]
Nope, can recreate it without using the global logger. Not sure why all the tests pass...
```python
import logging

import colorlog


def test_issue_36():
    formatter = colorlog.ColoredFormatter(
        '{log_color}{levelname}:{name}:{message}{reset}', style='{')

    handler = logging.StreamHandler()
    handler.setFormatter(formatter)

    logger = logging.getLogger('test_issue_36')
    logger.addHandler(handler)
    logger.error('test_issue_36')


if __name__ == '__main__':
    test_issue_36()
```

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 987, in emit
    msg = self.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 833, in format
    return fmt.format(record)
  File "/home/sam/Development/borntyping/python-colorlog/colorlog/colorlog.py", line 131, in format
    message = super(ColoredFormatter, self).format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 573, in format
    s = self.formatMessage(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 542, in formatMessage
    return self._style.format(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 394, in format
    return self._fmt.format(**record.__dict__)
KeyError: 'reset'
Call stack:
  File "./colorlog/tests/test_issues.py", line 19, in <module>
    test_issue_36()
  File "./colorlog/tests/test_issues.py", line 15, in test_issue_36
    logger.error('test_issue_36')
Message: 'test_issue_36'
Arguments: ()
```

**Comment by borntyping** [comment]
I've managed to add some tests that catch this - this has actually never worked as expected.

Bracket (`{`) and template (`$`) style formats don't work when you add color codes (e.g. `reset`, `blue,bold`) directly to the format string. Percent (`%`) style formats work fine. This means only Python 3 is affected, but 3.4, 3.5 and 3.6 are all affected.

https://travis-ci.org/borntyping/python-colorlog/builds/191325455

**Comment by borntyping** [comment]
This should work correctly now, with the removal of `parse_colors`: https://github.com/borntyping/python-colorlog/commit/604110371c60211fea0edfb86b866e4126f8878f
