### ISSUE TITLE
Feature: Custom level

### ISSUE THREAD

**Issue by AresS31** [borntyping/python-colorlog#45]
Hi,

If already supported, could you please detail how to set a custom logging level with an associated color and formatting? Otherwise that would be a nice addition!

Thanks

**Comment by AresS31** [comment]
Has any progress been made regarding that request?

**Comment by borntyping** [comment]
I think this should be doable with the existing `logging` library (see [`addLevelName()`](https://docs.python.org/3/library/logging.html#logging.addLevelName)), and then including that level in the `log_colors` argument to a `ColoredFormatter`.


```python
logging.addLevelName(1, 'TRACE')

...

formatter = ColoredFormatter(
	"%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s",
	log_colors={
		'TRACE':    'magenta',
		'DEBUG':    'cyan',
		'INFO':     'green',
		'WARNING':  'yellow',
		'ERROR':    'red',
		'CRITICAL': 'red,bg_white',
	}
)
```

**Comment by AresS31** [comment]
@borntyping thanks for your reply, if doable, could you please add a working example into the README.

Many thanks,
Alex

**Comment by borntyping** [comment]
https://github.com/borntyping/python-colorlog#with-custom-log-levels :smile:

**Comment by AresS31** [comment]
@borntyping I have been trying this way of achieving custom colored level, but I am encountering an issue. I believe that this issue is related to the background color which does not behave very well.

This is the code I am using:
```
import colorlog, logging

SUCCESS = 21

logging.addLevelName(SUCCESS, "SUCCESS")

def success(self, message, *args, **kws):
    if self.isEnabledFor(SUCCESS):
        self._log(SUCCESS, message, args, **kws) 

logging.Logger.success = success

FAILURE = 22

logging.addLevelName(FAILURE, "FAILURE")

def failure(self, message, *args, **kws):
    if self.isEnabledFor(FAILURE):
        self._log(FAILURE, message, args, **kws) 

logging.Logger.failure = failure

formatter = colorlog.ColoredFormatter(
    "%(log_color)s[%(asctime)s] [%(levelname)s] %(message)s%(reset)s",
    datefmt = "%H:%M:%S",
    log_colors = {
        'DEBUG':    'cyan',
        'INFO':     'green',
        'SUCCESS':  'red',
        'FAILURE':  'blue',
        'WARNING':  'yellow',
        'ERROR':    'red',
        'CRITICAL': 'red, bg_white'
    },
    reset = True
)

handler = logging.StreamHandler()
handler.setFormatter(formatter)

logger = logging.getLogger("TinderSwiper")
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)

logger.debug("DEBUG")
logger.info("INFO")
logger.success("SUCCES")
logger.failure("FAILURE")
logger.warning("WARNING")
logger.error("ERROR")
logger.critical("CRITICAL")
```
This is the exception being thrown:
```
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\logging\__init__.py", line 987, in emit
    msg = self.format(record)
  File "C:\Program Files\Python36\lib\logging\__init__.py", line 833, in format
    return fmt.format(record)
  File "C:\Program Files\Python36\lib\site-packages\colorlog\colorlog.py", line 119, in format
    record.log_color = self.color(self.log_colors, record.levelname)
  File "C:\Program Files\Python36\lib\site-packages\colorlog\colorlog.py", line 114, in color
    return parse_colors(log_colors.get(level_name, ""))
  File "C:\Program Files\Python36\lib\site-packages\colorlog\escape_codes.py", line 60, in parse_colors
    return ''.join(escape_codes[n] for n in sequence.split(',') if n)
  File "C:\Program Files\Python36\lib\site-packages\colorlog\escape_codes.py", line 60, in <genexpr>
    return ''.join(escape_codes[n] for n in sequence.split(',') if n)
KeyError: ' bg_white'
Call stack:
  File ".\test.py", line 67, in <module>
    logger.critical("CRITICAL")
Message: 'CRITICAL'
Arguments: ()
```

The corresponding screenshot:
![image](https://user-images.githubusercontent.com/11601622/28581793-29eeeb82-715b-11e7-9793-2bed2a49f0fe.png)

**Comment by borntyping** [comment]
Ah, I think I've broken anything that uses multiple colors (e.g. `red,bg_white`).

**Comment by borntyping** [comment]
This should be fixed by https://github.com/borntyping/python-colorlog/commit/02410e5eedcd5994cfddc1adffb82b5429d991f0 and https://github.com/borntyping/python-colorlog/commit/39677296066d4c72e86a119af0def6f9b7a64843.
