### ISSUE TITLE
colorlog.LevelFormatter does not allow to use dict for fmt parameter on python 3.8

### ISSUE THREAD

**Issue by PanovEduard** [borntyping/python-colorlog#77]
Traceback (most recent call last):
  File "D:/gitrep/DevOpsCI/DiasoftBuild/DiasoftBuild.py", line 36, in <module>
    from LogInit import file_formatter
  File "D:\gitrep\DevOpsCI\DiasoftBuild\CommonLib\LogInit.py", line 98, in <module>
    formatter = LevelFormatter(
  File "C:\Users\panov-ea\AppData\Roaming\Python\Python38\site-packages\colorlog\colorlog.py", line 160, in __init__
    super(LevelFormatter, self).__init__(
  File "C:\Users\panov-ea\AppData\Roaming\Python\Python38\site-packages\colorlog\colorlog.py", line 91, in __init__
    super(ColoredFormatter, self).__init__(fmt, datefmt, style)
  File "C:\Users\panov-ea\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 576, in __init__
    self._style.validate()
  File "C:\Users\panov-ea\AppData\Local\Programs\Python\Python38-32\lib\logging\__init__.py", line 456, in validate
    for _, fieldname, spec, conversion in _str_formatter.parse(self._fmt):
  File "C:\Users\panov-ea\AppData\Local\Programs\Python\Python38-32\lib\string.py", line 261, in parse
    return _string.formatter_parser(format_string)
TypeError: expected str, got dict

**Comment by leroy627** [comment]
Seems like Python-logging was updated in 3.8 with validation checks.
https://github.com/python/cpython/pull/9703

Adding a validate=false flag into the logging.formatter initializer for Python >= 3.8 should fix it

In my case, I just commented out the validate call in my logging lib.

**Comment by borntyping** [comment]
Could you provide a minimal code example you would expect to work? I'm very unclear on what usage would require passing a dictionary instead of a string as the `fmt` parameter.

**Comment by leroy627** [comment]
> Could you provide a minimal code example you would expect to work? I'm very unclear on what usage would require passing a dictionary instead of a string as the `fmt` parameter.

The LevelFormatter class seems to have specifically built in support for dicts as the `fmt` parameter
https://github.com/borntyping/python-colorlog/blob/809e8960f486398324cc049a6bef77fe738877c0/colorlog/colorlog.py#L133
There's an example there. Perhaps it could be reworked to not store the dict into fmt, but that would seem like it's just a complicated way of bypassing the validation check.

**Comment by borntyping** [comment]
My mistake, it's a long time since I've looked at the code for `LevelFormatter` and the original issue wasn't very clear.

**Comment by borntyping** [comment]
Fix released as version 4.1.0: https://pypi.org/project/colorlog/4.1.0/
